### PR TITLE
Fixed issue with BADA performance in descent (2nd attempt)

### PR DESCRIPTION
**Pull request by rmonstein**
This is a duplicate of PR #340 and the text below is copy-pasted from there. The reason for the duplicate is that this PR is based on the laterst state of the master branch.

@junzis and @ProfHoekstra, could you have another look at it?

---------------------------

Fixed an issue with the BADA performance model in descent where the model did not manage to match the vertical rate. It is now possible to descent with as little power as idle.

As far as I understood, one of the issues was that the member bs.traf.actwp.vs was set correctly in the method Autopilot.ComputeVNAV() and then (incorrectly) overwritten in Autopilot.update(). Additionally, the BADA model did not always correctly compute the thrust at negative vertical rates.

NOTE: the changes should be reviewed. I'm quite sure they are correct, but a second pair of eyes wouldn't hurt.

### CODE REVIEW

**Comment by junzis** [comment]
I am not sure if it is safe to remove the decorator `@timed_function(name="performance", dt=settings.performance_dt, manual=True)` for the update function in `perfbase.py`. 

I believe this is an important function for simulation.

@jooste, please have a look.

**Comment by rmonstein** [comment]
You are absolutely right. I don't know how these changes managed to sneak into the commit and I will remove them. The changes should only be to `autopilot.py ` and `perfbada.py`.

**Comment by rmonstein** [comment]
The PR now contains only the intended changes. Thank you for pointing this out @junzis.

**Comment by junzis** [comment]
The performance fix seems to be good with me. I will leave Jacco and Joost to check the autopilot part.

**Comment by ProfHoekstra** [comment]
The autopilot will be fixed in the next autopilot update, which is currently being tested before it is committed. (The autopilot fix as in the pull request led to problems in other situations in the current structure.)

**Comment by jooste** [comment]
Hi @rmonstein, The perfbada commit is fine, but your autopilot solution turned out to be more difficult, @ProfHoekstra is making / has made a solution for that. If you remove the changes to autopilot from your pull request I will merge the changes to perfbada!

**Comment by rmonstein** [comment]
Hi @jooste, the conflict should be resolved now and you can merge the PR when you find the time. Thanks

**Pull request merged**
