### PR TITLE
Fixed issue with BADA performance in descent

### PR DESCRIPTION
**Pull request by rmonstein**
Fixed an issue with the BADA performance model in descent where the model did not manage to match the vertical rate. It is now possible to descent with as little power as idle.

As far as I understood, one of the issues was that the member `bs.traf.actwp.vs` was set correctly in the method `Autopilot.ComputeVNAV()` and then (incorrectly) overwritten in `Autopilot.update()`. Additionally, the BADA model did not always correctly compute the thrust at negative vertical rates.

NOTE: the changes should be reviewed. I'm quite sure they are correct, but a second pair of eyes wouldn't hurt.

### CODE REVIEW

**Comment by jooste** [comment]
Hi @rmonstein, thanks for the PR. It has a couple of issues, however, and indeed the autopilot and perfbada suggestions need to be reviewed. You should also first update to the current version of the bluesky master, because right now your PR tries to undo a bugfix commit in autopilot.py. Also this PR includes wrong changes in perfbase and the notebook example. I commented on these in PR #341. @ProfHoekstra, can you have a look at the suggestion about a possible erroneous overwrite of data in autopilot.update? @junzis, can you see if the proposed change in perfbada makes sense?

**Comment by ProfHoekstra** [comment]
Good find. The update function of the autopilot was at some point scheduled at a different frequency than update_fms, that's why it was done at two locations. This change in scheduling however has caused a lot of problems (liek aircraft returning at the end of the route to the last waypoint), so it has been reverted and both update as well as update_fms are called synchronously. This makes this second call indeed unnecessary. I'll fix it. Thanks!

**Comment by junzis** [comment]
@rmonstein, it seems that the merging with main branch overwrote some of your code in the first commit. Would you please make a new PR based on the most recent main branch of BlueSky?

**Comment by rmonstein** [comment]
Thank you all. I will create a new PR based on the current version of the master soon and will duplicate the changes I made.

**Comment by rmonstein** [comment]
Closing this PR in favour of #342.

**Pull request closed without merging**
